# Generated by Django 5.2.16 on 2026-07-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(help_text='Vehicle Name/Model', max_length=100)),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Truck'), ('VAN', 'Van'), ('BIKE', 'Bike'), ('TRAILER', 'Trailer'), ('CAR', 'Car')], default='VAN', max_length=20)),
                ('max_load_capacity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('IN_SHOP', 'In Shop'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
